name: flutter_provider
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">= 1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.12
  flutter_hooks: ^0.9.0
  provider:
    path: ../provider

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
