name: provider_hooks
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  state_notifier: ^0.4.0
  freezed_annotation: ^0.7.1

dev_dependencies:
  flutter_hooks: ^0.9.0
  freezed: ^0.10.6
  build_runner: ^1.8.1
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter