name: hooks_riverpod
description: A new Flutter package project.
version: 0.0.1-pre+1
author:
homepage:

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter_riverpod:
    path: ../flutter_riverpod
  flutter:
    sdk: flutter
  flutter_hooks: ^0.9.0
  collection: ^1.14.12

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
