name: hooks_riverpod
description: >
  A simple way to access state from anywhere in your application
  while robust and being testable.version: 0.0.1-pre+1
homepage: https://riverpod.dev
authors:
  - Remi Rousselet <darky12s@gmail.com>

environment:
  sdk: ">=2.8.0-dev <3.0.0"

dependencies:
  flutter_riverpod:
    path: ../flutter_riverpod
  flutter:
    sdk: flutter
  flutter_hooks:
    path: /Users/remiguest/dev/flutter_hooks
  collection: ^1.14.12

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
