name: riverpod
description: A new Flutter package project.
version: 0.0.1-pre
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  collection: ^1.14.12
  freezed_annotation: ^0.7.1
  state_notifier: ^0.4.0

dev_dependencies:
  mockito: ^4.1.0
  test: ^1.14.2
  freezed: ^0.10.6
  build_runner: ^1.8.1
  trotter: ^1.2.0