name: flutter_riverpod
description: A new Flutter package project.
version: 0.0.1-pre+1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">= 1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.12
  state_notifier: ^0.4.0
  riverpod: 0.0.1-pre+1

dev_dependencies:
  mockito: ^4.1.0
  flutter_test:
    sdk: flutter
